### ISSUE TITLE
How to set formatter?

### ISSUE THREAD

**Issue by SunDoge** [brmmm3/fastlogging#1]
This logging library is indeed faster than standard logging. However, there seems no way to custom the output message like 

```
LOG_FORMAT = '%(asctime)s|%(levelname)-8s|%(filename)s:%(lineno)d %(message)s'
```

Will it be supported in the future?

**Comment by brmmm3** [comment]
You can set a custom formatter callback function through:
Logger.cbFormatter = <cbFunc>

cbFunc must be defined as:

def cbFunc(self, entry):
   ...
   return message

Where self is the logger instance and entry is a tuple:
entry = (logTime, domain, level, msg, kwargs)
The function must return the formatted string to be logged.

IMHO a callback function is more powerfull than a format string.

Does it solve your problem?

**Comment by SunDoge** [comment]
Thx.

**Comment by ansarid** [comment]
@SunDoge Would you be able to provide an example demonstrating this functionality? I'm not having any success making it work, but I think that's because of my lack of experience. An example demonstrating this would be very helpful.

**Comment by SunDoge** [comment]
@ansarid 

```python
from fastlogging import Logger, LogInit

Logger.cbFormatter = lambda self, entry: f'{entry}'

logger = LogInit(console=True, colors=True, pathName='/tmp/test.log')
logger.info('something')
```

**Comment by ansarid** [comment]
@SunDoge Thank you, that's perfect! Thank you for the extremely quick response!

**Comment by kootenpv** [comment]
How to make this work with:

```
import time
import logging

formatter = logging.Formatter("%(asctime)s [%(levelname)s] %(message)s")
setattr(formatter, "converter", time.gmtime)

logger = logging.getLogger()
stdout = logging.StreamHandler(sys.stdout)
stdout.setFormatter(formatter)
```
