### ISSUE TITLE
EXCEPTION doesn't get a color and outputs a suplementary number '50'

### ISSUE THREAD

**Issue by Ariimeow78** [brmmm3/fastlogging#15]
<strike>Also just a quick mention, I don't want to create another issue just for this, as it's just a question for now:</strike> Nevermind.

Is it normal for `exception()` to write that `50` before the date is printed? The other levels don't show that 50, so I just assumed there might be a mistake.

And another quick mention:
At file fastlogging.py line 66 and 73:
```py
DARKORANGE = chr(27) + "[50m"
ORANGE = Style.BRIGHT + DARKORANGE
```
There's no such thing as Orange in ANSI colors.  There's only Yellow and Bright Yellow.
And `ESC[50m` isn't a reserved sequence.

EXCEPT also doesn't seem to get any colors per line 97. Perhaps that's why it prints that '50' before the datetime.
## Edit: Yes it does.

I modified this line with a placeholder color like this:
```py
LVL2COL = {EXCEPTION: Colors.CYAN, FATAL: Colors.RED, ERROR: Colors.DARKRED, WARNING: Colors.YELLOW, INFO: Colors.GREEN, DEBUG: Colors.WHITE}
```
and it works as expected:

![image](https://github.com/user-attachments/assets/85e4d91f-a657-40d9-9fbd-6c31adb41288)

_Ps: Sorry for creating so many issues, I don't mean to spam or anything, I'm just suprised this project hasn't got very popular yet._

**Comment by brmmm3** [comment]
Fixed in 1.2.0
