### ISSUE TITLE
log order not right

### ISSUE THREAD

**Issue by DNACore** [brmmm3/fastlogging#2]
The logs printed by the console are not always printed in the order in which they are coded.

python：3.7.4

```python
    logger = LogInit(console=True, colors=False)
    while True:
        logger.debug('this is a debug message')
        logger.info('this is a info msg')
        logger.warning('this is a warning msg')
        logger.error('this is a error msg')
        logger.fatal('this is a fatal msg')
        logger.critical('this is a critical msg')
        time.sleep(1)
```

the consol

> 19.09.24 16:41:26: root: DEBUG  : this is a debug message
> 19.09.24 16:41:26: root: INFO   : this is a info msg
> 19.09.24 16:41:26: root: WARNING: this is a warning msg
> 19.09.24 16:41:26: root: ERROR  : this is a error msg
> 19.09.24 16:41:26: root: FATAL  : this is a fatal msg
> 19.09.24 16:41:26: root: FATAL  : this is a critical msg
> 19.09.24 16:41:27: root: ERROR  : this is a error msg
> 19.09.24 16:41:27: root: DEBUG  : this is a debug message
> 19.09.24 16:41:27: root: FATAL  : this is a fatal msg
> 19.09.24 16:41:27: root: FATAL  : this is a critical msg
> 19.09.24 16:41:27: root: INFO   : this is a info msg
> 19.09.24 16:41:27: root: WARNING: this is a warning msg
> 19.09.24 16:41:28: root: DEBUG  : this is a debug message
> 19.09.24 16:41:28: root: INFO   : this is a info msg
> 19.09.24 16:41:28: root: WARNING: this is a warning msg
> 19.09.24 16:41:28: root: ERROR  : this is a error msg
> 19.09.24 16:41:28: root: FATAL  : this is a fatal msg
> 19.09.24 16:41:28: root: FATAL  : this is a critical msg
> 19.09.24 16:41:29: root: DEBUG  : this is a debug message
> 19.09.24 16:41:29: root: INFO   : this is a info msg
> 19.09.24 16:41:29: root: WARNING: this is a warning msg
> 19.09.24 16:41:29: root: ERROR  : this is a error msg
> 19.09.24 16:41:29: root: FATAL  : this is a fatal msg
> 19.09.24 16:41:29: root: FATAL  : this is a critical msg
> 19.09.24 16:41:30: root: ERROR  : this is a error msg
> 19.09.24 16:41:30: root: DEBUG  : this is a debug message
> 19.09.24 16:41:30: root: FATAL  : this is a fatal msg
> 19.09.24 16:41:30: root: FATAL  : this is a critical msg
> 19.09.24 16:41:30: root: INFO   : this is a info msg
> 19.09.24 16:41:30: root: WARNING: this is a warning msg
> 19.09.24 16:41:31: root: DEBUG  : this is a debug message
> 19.09.24 16:41:31: root: INFO   : this is a info msg
> 19.09.24 16:41:31: root: ERROR  : this is a error msg
> 19.09.24 16:41:31: root: FATAL  : this is a fatal msg
> 19.09.24 16:41:31: root: FATAL  : this is a critical msg
> 19.09.24 16:41:31: root: WARNING: this is a warning msg

**Comment by brmmm3** [comment]
Which OS did you use? Did you use the latest Version of fastlogging?
I've tried to reproduce the bug on Linux, but I couldn't.

**Comment by DNACore** [comment]
> Which OS did you use? Did you use the latest Version of fastlogging?
> I've tried to reproduce the bug on Linux, but I couldn't.

The system is macOS 10.14.6. And the fastlogging is the latest Version.
I tried this in PyCharm.

**Comment by brmmm3** [comment]
I've seen this behavior too. But this is an issue of PyCharm. If you run this example in the console window you'll see the correct log order. The reason is that everything up to warning level is printed to stdout and error and fatal levels are printed to stderr.
