### ISSUE TITLE
HOW-TO: callback to notifiers

### ISSUE THREAD

**Issue by airmonitor** [brmmm3/fastlogging#3]
Hello.

Can you please advise if there is a possibility to use a python notifiers library with fastlogging?

My goal is to use notifiers to push warn, error, critical severity messages to slack via notifier library as described in https://notifiers.readthedocs.io/en/latest/Logger.html

Thank you
Tom

**Comment by brmmm3** [comment]
Interesting. I'll have a look at it.

**Comment by brmmm3** [comment]
Please checkout the branch 'notifier' and test it. I've added an example for this.

**Comment by airmonitor** [comment]
Hi @brmmm3 
Thx for adding change there :)

I've tested using slack as target recipient and I noticed that console color is also sent there:
`[1m[32m20.02.07 23:27:06: root: INFO   : And just like that, you get notified about all your errors![0m`

Is there any way to have colors in the console but color code will not be sent to notifiers?

Additional question is how can I specify that only error and above will be sent via slack?

Thank you
Tom

**Comment by brmmm3** [comment]
I've updated the branch. Please test it if it's fine now.
I've also updated the example ex_notifier.py which shows now how to set different log levels.

**Comment by airmonitor** [comment]
Thx!

Seems to be working without hassle :)
