### ISSUE TITLE
[Unexpected Behaviour] Issue with log rotation

### ISSUE THREAD

**Issue by sriharsha-simility** [brmmm3/fastlogging#4]
Hi Team,
We are trying to integrate fastlogging into our python applications. While doing intial tests, we came across an issue when log file rotation is activated. 

<img width="806" alt="Screenshot 2020-08-21 at 1 34 29 PM" src="https://user-images.githubusercontent.com/52438643/90867549-2bb2a300-e3b3-11ea-925b-a3e6aba52af9.png">

Although exampe1.log file gets created it is empty.
<img width="1438" alt="Screenshot 2020-08-21 at 1 30 11 PM" src="https://user-images.githubusercontent.com/52438643/90867082-77b11800-e3b2-11ea-82a7-0931ff2db836.png">

We are using python 3.6.10
fastlogging==0.9.4
Cython==0.28.5

**Comment by brmmm3** [comment]
Problem should be fixed in 0.9.5.

**Comment by div338** [comment]
Hi, Is this fixed?

**Comment by brmmm3** [comment]
Problem is fixed in version 0.9.5. You have to update fastlogging package.
